version: '3.8'
services:

  cache:
    container_name: cache-container-employees
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass eYVX7EwVmmxKPCDmwMtyKVge8oLd2t81maybeunsafe
    volumes:
      - cache:/data

  db:
    container_name: ps-container-employees
    image: postgres:13.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=${EMPLOYEE_DB_USER}
      - POSTGRES_PASSWORD=${EMPLOYEE_DB_PASSWORD}
      - POSTGRES_DB=employees=${EMPLOYEE_DB_NAME}
    ports:
      - '${EMPLOYEE_DB_PORT}:5432'
    volumes:
      - db:/ar/lib/postgresql/data

  elasticsearch:
    container_name: es-container-employees
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.1
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - '9200:9200'

volumes:
  cache:
    driver: local
  db:
    driver: local
# elasticsearch:
#    driver: local
